#! /bin/bash

file="$1"
if [ ! -e $file ]
then
	echo "file '$file' does not exist";
	exit 1
fi

author="Sharas"
base_name=$(basename $file); base_name=${base_name%.*};
out_file=${base_name}.html;
title=$(head -n 1 $file);
article=$(tail -n +2 $file);
html_content=$(markdown.pl <(echo "$article"));

cat - <<EOF > $out_file
<!DOCTYPE html>
<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
	<link href="style/main.css" media="screen" rel="stylesheet" type="text/css" />
	<title>${title}</title>
</head>
<body>
<span itemscope itemtype="http://schema.org/Article">
<div id="header">
	<h1 itemprop="name" id="title">${title}</h1>
	<h3 class="signature">
		By
		<span itemprop="author" itemscope itemtype="http://schema.org/Person" class="author">
		<span itemprop="givenName">${author}</span>
		</span>
		<a itemprop="sameAs" target="_blank" href="https://twitter.com/Sharas_">@Sharas_</a>
		on <span itemprop="dateCreated">$(date +"%B %d %Y")</span>
	</h3>
</div>
<div id="content" itemprop="text">
${html_content}
</div>
</span>
</body>
</html>
EOF
